### Задание 1.3.1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [1]:
import numpy as np

matrix = np.zeros(64, dtype=int).reshape(8,8)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Задание 1.3.2
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [2]:
row = np.arange(5)
matrix = np.tile(row,5).reshape(5,5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Задание 1.3.3
Создать массив 3x3x3 со случайными значениями.

In [3]:
array = np.random.random((3,3,3))
print(array)

[[[0.56727206 0.93245728 0.7189294 ]
  [0.02017733 0.05798435 0.55356475]
  [0.28305846 0.89509798 0.78541987]]

 [[0.11250268 0.58780794 0.66584693]
  [0.86221583 0.64962027 0.01232793]
  [0.29795945 0.7809163  0.50403349]]

 [[0.52486683 0.16225046 0.15102925]
  [0.25576829 0.02631951 0.36374718]
  [0.48769125 0.63492777 0.33998657]]]


### Задание 1.3.4
Создать матрицу с 0 внутри, и 1 на границах.

In [4]:
n = int(input("Размерность матрицы: "))
matrix = np.zeros(n*n, dtype=int).reshape(n,n)
matrix[-1::],matrix[::,-1::], matrix[0:1:],matrix[::,0:1:] = 1,1,1,1
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Задание 1.3.5
Создайте массив и отсортируйте его по убыванию.

In [ ]:
array = np.array([2,4,5,3,12,4,0,7])
array = np.sort(array)[::-1]
print(array)

[12  7  5  4  4  3  2  0]


### Задание 1.3.6
Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
matrix = np.arange(25).reshape(5,5)

print("Форма", matrix.shape)
print("Размер", matrix.size)
print("Размерность", matrix.ndim)

Форма (5, 5)
Размер 25
Размерность 2


### Задание 2.3.1
Найдите Евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [6]:
import pandas as pd
import numpy as np

a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

squared_diff = (a - b) ** 2
sum_squared_diff = np.sum(squared_diff)
euclidean_distance = np.sqrt(sum_squared_diff)
print(euclidean_distance)


5.196152422706632


### Задание 2.3.2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets ). Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'

df = pd.read_csv(url)

print(df.head(2))
print('-----------------------------------------------------------------------')
print(df.tail(3))
print('-----------------------------------------------------------------------')
print(df.shape)
print('-----------------------------------------------------------------------')
print(df.describe())
print('-----------------------------------------------------------------------')
print(df.iloc[2:5])
print('-----------------------------------------------------------------------')
print(df[df['Airline'] == 'US'].head(2))

  Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
-----------------------------------------------------------------------
       Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1
-----------------------------------------------------------------------
(539383, 8)
-----------------------------------------------------------------------
              Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     2

### Задание 2.3.3
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [7]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

df = pd.read_csv(url)

minmax_scaler = MinMaxScaler()
df['sepal_length_cm_normalized'] = minmax_scaler.fit_transform(df[['sepal_length_cm']])

standard_scaler = StandardScaler()
df['sepal_width_cm_scaled'] = standard_scaler.fit_transform(df[['sepal_width_cm']])

print(df.head())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species  \
0              5.1             3.5              1.4             0.2  setosa   
1              4.9             3.0              1.4             0.2  setosa   
2              4.7             3.2              1.3             0.2  setosa   
3              4.6             3.1              1.5             0.2  setosa   
4              5.0             3.6              1.4             0.2  setosa   

   sepal_length_cm_normalized  sepal_width_cm_scaled  
0                    0.222222               1.032057  
1                    0.166667              -0.124958  
2                    0.111111               0.337848  
3                    0.083333               0.106445  
4                    0.194444               1.263460  
